// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqemgtE81vnqOvknBDmGZzVhYWowlaxOE',
    appId: '1:171963578595:web:8b4146168f9db96f6eadd6',
    messagingSenderId: '171963578595',
    projectId: 'coleta-plus-scu',
    authDomain: 'coleta-plus-scu.firebaseapp.com',
    storageBucket: 'coleta-plus-scu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHJxWClFL0ItKDR6t-aIcLQi3wMviSspM',
    appId: '1:171963578595:android:4c7397a52092c8606eadd6',
    messagingSenderId: '171963578595',
    projectId: 'coleta-plus-scu',
    storageBucket: 'coleta-plus-scu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASeUz0OBvapXpXD9BK2cvA4z5Pq635nfU',
    appId: '1:171963578595:ios:01cec0e4279239726eadd6',
    messagingSenderId: '171963578595',
    projectId: 'coleta-plus-scu',
    storageBucket: 'coleta-plus-scu.firebasestorage.app',
    iosBundleId: 'com.mycompany.coletaplus',
  );
}
