// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE5HcAEX_Be7_2Tci0Jtmtmu9K6evnWOY',
    appId: '1:458717794730:web:8bf8a7c0abc13ab9f51bd3',
    messagingSenderId: '458717794730',
    projectId: 'coleta-plus-2xp90b',
    authDomain: 'coleta-plus-2xp90b.firebaseapp.com',
    storageBucket: 'coleta-plus-2xp90b.firebasestorage.app',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmL3U-4E2LImCeH-moAmOoaSip3-cDg60',
    appId: '1:458717794730:android:7bc6a2477ce609f5f51bd3',
    messagingSenderId: '458717794730',
    projectId: 'coleta-plus-2xp90b',
    storageBucket: 'coleta-plus-2xp90b.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOu1LazoaYl6GXtjpZ5srp3pgKzTVbSFg',
    appId: '1:458717794730:ios:ea07a5b1e1429b79f51bd3',
    messagingSenderId: '458717794730',
    projectId: 'coleta-plus-2xp90b',
    storageBucket: 'coleta-plus-2xp90b.firebasestorage.app',
    iosBundleId: 'com.mycompany.coletaplus',
  );
}
